// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using v2en.Data;

#nullable disable

namespace v2en.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715054500_AddChatGptTranslation")]
    partial class AddChatGptTranslation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("v2en.Data.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("v2en.Data.FeedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastETag")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastFetchUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSourceFeedUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QuotaWindowResetUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslationsToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FeedStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TranslationsToday = 0
                        });
                });

            modelBuilder.Entity("v2en.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorUri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentEnHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentZhHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTagId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleZh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TranslatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationModel")
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("V2exId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Published");

                    b.HasIndex("V2exId")
                        .IsUnique();

                    b.HasIndex("Status", "Published");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("v2en.Data.PostEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dim")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EmbeddedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Vector")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .IsUnique();

                    b.ToTable("PostEmbeddings");
                });

            modelBuilder.Entity("v2en.Data.RuntimeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatGptAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ChatGptAccessTokenExpiresUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatGptAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatGptAccountLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatGptIdToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatGptPlanType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatGptRefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatMaxContextPosts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChatModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChatRateLimitPerMinutePerIp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyQuota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmbedMaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmbedMaxPerTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmbeddingDim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableChat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeminiEmbedKeysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPerTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDelaySecondsBetweenCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenRouterApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RetrievalTopK")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<string>("TranslationFallbackModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationFallbackProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationFallbackReasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationPrimaryModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationPrimaryProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationPrimaryReasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UnlimitedDaily")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RuntimeSettings");
                });

            modelBuilder.Entity("v2en.Data.TranslationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Utc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("V2exId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("Utc");

                    b.ToTable("TranslationLogs");
                });

            modelBuilder.Entity("v2en.Data.PostEmbedding", b =>
                {
                    b.HasOne("v2en.Data.Post", "Post")
                        .WithOne("Embedding")
                        .HasForeignKey("v2en.Data.PostEmbedding", "PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("v2en.Data.Post", b =>
                {
                    b.Navigation("Embedding");
                });
#pragma warning restore 612, 618
        }
    }
}
