// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using v2en.Data;

#nullable disable

namespace v2en.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624102943_AdminDashboard")]
    partial class AdminDashboard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("v2en.Data.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastLoginUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("v2en.Data.FeedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastETag")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastFetchUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSourceFeedUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QuotaWindowResetUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslationsToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FeedStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TranslationsToday = 0
                        });
                });

            modelBuilder.Entity("v2en.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorUri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentEnHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentZhHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTagId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleZh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TranslatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationModel")
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("V2exId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Published");

                    b.HasIndex("V2exId")
                        .IsUnique();

                    b.HasIndex("Status", "Published");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("v2en.Data.RuntimeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DailyQuota")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPerTick")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDelaySecondsBetweenCalls")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<bool>("UnlimitedDaily")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RuntimeSettings");
                });

            modelBuilder.Entity("v2en.Data.TranslationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("Utc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("V2exId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Level");

                    b.HasIndex("Utc");

                    b.ToTable("TranslationLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
