// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using v2en.Data;

#nullable disable

namespace v2en.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("v2en.Data.FeedState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastETag")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastFetchUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSourceFeedUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("QuotaWindowResetUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TranslationsToday")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FeedStates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TranslationsToday = 0
                        });
                });

            modelBuilder.Entity("v2en.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorUri")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentEnHtml")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentZhHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirstSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<long>("Published")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceTagId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleZh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("TranslatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationModel")
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("V2exId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Published");

                    b.HasIndex("V2exId")
                        .IsUnique();

                    b.HasIndex("Status", "Published");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
